### ISSUE TITLE
Creating shared conda environments and singularity images on Cere

### ISSUE THREAD

**Issue by spcspin** [NAL-i5K/SRAtoVCF#3]
Because pipeline in Cere will need to set up conda environment and use singularity images, in order to save storage space to avoid multiple downloads, we can consider setting up a common environment and images.

**Comment by mpoelchau** [comment]
A good place for a shared environment on Ceres will be `/project/nal_genomics/shared_programs`

**Comment by spcspin** [comment]
A folder containing the conda environment and sif files has been created in the `shared_programs` folder called SRAtoVCF. The documentation for making the shared conda environment and sif files has been added in README.md file.
